#!/bin/sh

# if the branch is main, then fail.

branch="$(git symbolic-ref HEAD 2>/dev/null)" || \
  "$(git describe --contains --all HEAD)"

if [ "${branch##refs/heads/}" = "main" ]; then
  echo "Do not commit on the main branch!"
  exit 1
fi
